pointnetwork/social.point

- src/components/comments/Comments.jsx
- src/components/share/Share.jsx
This PR includes a small fix to set the cap up to 140 characters on posts and comments
> Implemented a max length cap of 140 characters for posts and comments

- src/components/comments/Comment.jsx
- src/components/comments/Comments.jsx
- src/components/comments/comments.css
- src/components/post/Post.jsx
- src/components/post/post.css
- src/components/share/Share.jsx
This PR includes a solution for the PZ-75 issue including support for multiline post and comments
> Implementation of multiline comments and posts

- src/components/topbar/Topbar.jsx
- src/components/topbar/topbar.css
This PR contains a small fix to allow top logo link functionality
> Small fix to allow visitors click on the logo and redirect to main page

- routes.json
Update routes.json to allow refresh on profile page.
> Refresh on profile page

- contracts/PointSocial.sol
- src/components/feed/Feed.jsx
- src/components/post/Post.jsx
- src/components/post/PostEditor.jsx
- src/components/post/post.css
- src/components/post/postEditor.css
- src/components/share/Share.jsx
This PR includes the feature that allows to edit posts in social.point
- Only the owner can edit the post
- The posts could be only edited if there is no comments
- It is possible to change the text content and the image/media file
> Pz 134 ability to edit exiting posts

- contracts/PointSocial.sol
- src/components/comments/Comment.jsx
- src/components/comments/CommentEditor.jsx
- src/components/comments/Comments.jsx
- src/components/comments/comments.css
This PR includes:
- The feature to edit existing comments
- Only the author can edit their specific comments
> Pz 136 ability to edit existing comments

- src/components/comments/Comment.jsx
- src/components/post/Post.jsx
This PR contains a small fix to link the users to their corresponding posts and comments
> Implemented link in Posts and Comments to their corresponding authors

- contracts/PointSocial.sol
- package.json
- src/components/comments/Comment.jsx
- src/components/comments/CommentEditor.jsx
- src/components/comments/Comments.jsx
- src/components/comments/comments.css
- src/components/feed/Feed.jsx
- src/components/post/Post.jsx
- src/pages/profile/Profile.jsx
This PR includes the functionality to delete user's comments
- Only the author is able to delete their comments.
> Pz 137 ability to delete existing comment

- contracts/PointSocial.sol
- package.json
- src/components/comments/Comment.jsx
- src/components/comments/CommentEditor.jsx
- src/components/comments/Comments.jsx
- src/components/comments/comments.css
- src/components/feed/Feed.jsx
- src/components/post/Post.jsx
- src/components/post/post.css
- src/components/share/Share.jsx
- src/pages/profile/Profile.jsx
This PR includes functionality for deleting posts from Social.point
- Only the owner can delete posts
- The post feed now uses pagination
- Implemented post reloading when posts are deleted
> Pz 135 ability to delete existing post

- contracts/PointSocial.sol
- package.json
- src/App.js
- src/components/profile/ProfileCard.jsx
- src/components/tabs/TabPanel.jsx
- src/components/topbar/Topbar.jsx
- src/context/AppContext.js
- src/pages/profile/Profile.jsx
This PR includes:
-  Refactoring of the profile page in favor of a new component (ProfileCard component)
-  New profile routing for identities in addition to addresses
- User profile information (users can view and edit):
- displayName   
- displayLocation
- displayAbout
- avatar
- banner
- Placeholder for new functionalities as followers and following count, likes feed and user's comments.
- Implementation of Material UI as the default design system for the ZApp, the idea is use Material UI elements
across all the components to maintain consistency.
- Support for different screen sizes (responsive design)
> Pz 138 create user profile page

- src/components/avatar/UserAvatar.jsx
- src/components/comments/CommentItem.jsx
- src/components/comments/CommentList.jsx
- src/components/feed/Feed.jsx
- src/components/post/PostCard.jsx
- src/components/profile/ProfileCard.jsx
- src/components/share/ShareCard.jsx
- src/context/AppContext.js
- src/pages/post/Post.jsx
- src/pages/profile/Profile.jsx
- src/services/CommentManager.js
- src/services/EventManager.js
- src/services/PointSDK.js
- src/services/PostManager.js
- src/services/UserManager.js
This PR contains helpers and convenience functions to interact with Point SDK, additionally, it sets a timeout limit to PointSDK requests, allowing to handle correctly some PointSDK issues that leave the application waiting forever (see PZ-242 and PZ-246)
> Implemented a timeout for all pointsdk requests

- src/components/feed/Feed.jsx
This PR fixes the jumping problem when loading new posts.
> Changes in the Feed component to avoid flickering and jumping

- src/services/PointSDK.js
This PR includes logging functionality for the PointSDK requests, having the option of 
setting the flag DEBUG=true to get a more verbose output from the PointSDK requests
> Included logging support for PointSDK calls

- src/components/generic/CardMediaSelector.jsx
This PR contains changes in CardMediaSelector to allow filtering of unsupported media formats, such as MKV
> Changes in CardMediaSelector to filter unsupported media formats

- src/services/CommentManager.js
- src/services/PostManager.js
- src/services/UserManager.js
This PR revert the changes to social point in order to support PointSDK version up to 0.0.10
> Reverted changes to support PointSDK up to v0.0.10

- contracts/PointSocial.sol
This PR includes a small change to support user's profile migration when using hardhat tasks.
> Included smartcontract function to migrate user profiles

- .gitignore
- contracts/Identity.sol
- contracts/PointSocial.sol
- hardhat.config.js
- package-lock.json
- package.json
- src/services/PointSDK.js
- tests/unit/smartcontracts/PointSocial.js
This PR contains changes to allow deployers to upgrade the proxy.
> Allow deployers to upgrade the proxy

- .github/workflows/deploy.yml
- scripts/entrypoint.sh
This PR contains a small correction for deploy action related to yaml syntax specifying the checkout path
> Fix checkout actions, debugging info for entrypoint.sh

- contracts/PointSocial.sol
- src/components/comments/CommentItem.jsx
- src/services/PointSDK.js
This PR contains a small change that shows a [Edited] label on comments when they were edited.
> Implemented edited label on comments

- src/components/footer/Footer.js
- src/components/share/ShareCard.jsx
This PR contains small fixes to text in footer and post component
> Minor fixes in footer and share component

- src/services/EventManager.js
- src/services/PostManager.js
This PR contains a small fix to solve the post editing error
> Fix post update action

- package-lock.json
- package.json
- src/components/generic/TextContent.jsx
- src/components/post/PostCard.jsx
This PR contains a modification for posts that allows to render correctly urls and user mentions ( with the at symbol @)
> Implemented rendering of URLS and user mentions

- contracts/PointSocial.sol
This PR contains a small fix for _getPostWithMetadata which caused some errors when retrieving posts.
> Fix function _getPostWithMetadata

- src/components/generic/CollapsibleTypography.jsx
- src/components/generic/TextContent.jsx
This PR contains the implementation of links for URL and profiles into comments, in addition, the detection of user profiles is capped up to 14 characters.
> Implemented links to URLs and profiles in comments

- src/components/comments/CommentItem.jsx
- src/components/comments/CommentList.jsx
- src/components/generic/RichTextField.jsx
- src/components/post/PostCard.jsx
- src/components/profile/ProfileCard.jsx
- src/components/share/ShareCard.jsx
- src/context/AppContext.js
This PR contains the implementation of a state flag that allows to lock certain state changing components during the emission of a new transaction, allowing to send only one transaction at once.
> PZ-239 Disable buttons while action is performed
